/**
 * DO NOT EDIT THIS FILE!
 * File automatically generated by
 *   build_tools/sim_object_param_struct_hh.py:50
 */

#ifndef __PARAMS__StraightRTC__
#define __PARAMS__StraightRTC__

namespace gem5 {
class StraightRTC;
} // namespace gem5
#include <cstddef>
#include <cstddef>
#include "base/types.hh"
#include <cstddef>
#include <time.h>

#include "params/SimObject.hh"

namespace gem5
{
struct StraightRTCParams
    : public SimObjectParams
{
    gem5::StraightRTC * create() const;
    bool bcd;
    Tick frequency;
    tm time;
    unsigned int port_int_pin_connection_count;
};

} // namespace gem5

#endif // __PARAMS__RiscvRTC__
