# Copyright (c) 2021 The Regents of the University of California
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('*')

SimObject('LupioBLK.py', sim_objects=['LupioBLK'], tags='straight isa')
SimObject('LupioIPI.py', sim_objects=['LupioIPI'], tags='straight isa')
SimObject('LupioPIC.py', sim_objects=['LupioPIC'], tags='straight isa')
SimObject('LupioRNG.py', sim_objects=['LupioRNG'], tags='straight isa')
SimObject('LupioRTC.py', sim_objects=['LupioRTC'], tags='straight isa')
SimObject('LupioTMR.py', sim_objects=['LupioTMR'], tags='straight isa')
SimObject('LupioTTY.py', sim_objects=['LupioTTY'], tags='straight isa')
SimObject('LupioSYS.py', sim_objects=['LupioSYS'], tags='straight isa')

DebugFlag('LupioBLK')
DebugFlag('LupioIPI')
DebugFlag('LupioPIC')
DebugFlag('LupioRNG')
DebugFlag('LupioRTC')
DebugFlag('LupioTMR')
DebugFlag('LupioTTY')
DebugFlag('LupioSYS')

Source('lupio_blk.cc', tags='straight isa')
Source('lupio_ipi.cc', tags='straight isa')
Source('lupio_pic.cc', tags='straight isa')
Source('lupio_rng.cc', tags='straight isa')
Source('lupio_rtc.cc', tags='straight isa')
Source('lupio_tmr.cc', tags='straight isa')
Source('lupio_tty.cc', tags='straight isa')
Source('lupio_sys.cc', tags='straight isa')
